config/routes.rb
Testapp::Application.routes.draw do

  devise_for :users

  root :to => 'staticpages#index'
  resources :pics
  resources :votes

end

app/models/pic.rb
class Pic < ActiveRecord::Base
   attr_accessible :hour, :emotion, :learned, :image
   has_many :votes
   mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :mode, :pic_id
  belongs_to :pic
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
	def index
		@pics = Pic.all
	end

	def new
		@pic = Pic.new
	end

	def create
		@pic = Pic.create(params[:pic])
		redirect_to pics_path
	end
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController

	def index
	end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
	def create
		# params[:pic_id], params[:mode]
		Vote.create(:pic_id => params[:pic_id], :mode => params[:mode])
		redirect_to pics_url
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application", "backstretch" %>
  <%= csrf_meta_tags %>




</head>
<body>

<script>
	$(function() {
		 $.backstretch([
		"/assets/panoramic_boston.jpg"
		, "/assets/new_york_skyline-wide.jpg"
		, "/assets/providence-warwick-convention.jpg"
		], {duration: 3000, fade: 750});
	});
</script>

<div class="navbar navbar-inverse">
	  <div class="navbar-inner">
		    <div class="container">
			      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
			      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				        <span class="icon-bar"></span>
				        <span class="icon-bar"></span>
				        <span class="icon-bar"></span>
			      </a>
			 
			      <!-- Be sure to leave the brand out there if you want it shown -->
			      <a class="brand" href="<%=root_path %>">FireHose Project</a>
			 
			      <!-- Everything you want hidden at 940px or less, place within here -->
			      <div class="nav-collapse collapse">
			        	<!-- .nav, .navbar-search, .navbar-form, etc -->
			        	<ul class="nav">
			        		<li><%= link_to 'My App', pics_path %></li>
			        		<li><%= link_to 'New Picture', new_pic_path %></li>
			        	</ul>
			        	<ul class="nav pull-right">
			        		<% if current_user.present? %>
			        			<li>
			        				<%= link_to current_user.email, '#' %>
			        			</li>
			        			<li>
			        				<%= link_to "sign out", destroy_user_session_path, :method => :delete %>
			        			</li>
			        		<% else %>
			        			<li><%= link_to 'Sign in', new_user_session_path %></li>
			        			<li><%= link_to 'Sign up', new_user_registration_path %></li>
			        		<% end %>

			        	</ul>
			      </div>
		    </div>
	  </div>
</div>

<% if notice.present? %>
	<p class="notice"><%= notice %></p>
<% end %>
<% if alert.present? %>
	<p class="alert"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/pics/index.html.erb
<div class="my-wrapper">
	<h1>My Pics</h1>

	<% @pics.each do |pic| %>
		<div class="span3 box text-center">
			<h2>
				Hour <%= pic.hour %> <br />
			</h2>

			<div>
				<%= image_tag pic.image %>
			</div>

			<h3>
				I feel <%= pic.emotion %>
			</h3>
			<p>
				I learned that <%= pic.learned %>
			</p>
			<%= link_to 'Vote Up', votes_path(:pic_id => pic.id, :mode => 1), :method => :post %> |
			<%= link_to 'Vote down', votes_path(:pic_id => pic.id, :mode => -1), :method => :post  %> 



			<p>Total: <%= pic.votes.sum(&:mode) %> </p>
		</div>
	<% end %>
</div>

app/views/pics/new.html.erb
<div class="span6 offset3 text-center stolen-surfbox">
<h1>Upload Your Pic</h1>

	<%= simple_form_for @pic do |f| %>
		<%= f.input :hour %>
		<%= f.input :image, :as => :file %>
		
		<%= f.input :emotion, :label => 'mood' %>
		<%= f.input :learned, :input_html => {:rows => 10} %>
		<%= submit_tag "Save", :class => "btn btn-primary btn-large" %>
	<% end %>
</div>

app/views/staticpages/index.html.erb
<div class="span6 offset3 text-center stolen-surfbox">
	<h1 class="custom-font-1">Hello I'm Phil</h1>
		<br />
	<h2 class="custom-font-2">I'm having a lot of fun learning how to code at the firehose weekend</h2>

	<%= link_to "Launch App", "#", :class => ('btn btn-large btn-primary') %>
</div>